.TH wiki 1 "February 28, 2021" "v1.0" "Made for CSI"
.SH NAME
wiki - summarize Wikipedia pages
.SH USAGE
wiki SEARCHTERM [SUBSECTION]
.SH EXAMPLES

$ ./wiki walrus

You searched for 'walrus'
Found this wiki page: 'https://en.wikipedia.org/wiki/Walrus'.

First paragraph:

The walrus (Odobenus rosmarus) is a large flippered marine mammal with a discontinuous distribution about the North Pole in the Arctic Ocean and subarctic seas of the Northern Hemisphere. The walrus is the only living species in the family Odobenidae and genus Odobenus. This species is subdivided into two subspecies:&#91;2&#93; the Atlantic walrus (O. r. rosmarus), which lives in the Atlantic Ocean, and the Pacific walrus (O. r. divergens), which lives in the Pacific Ocean.

Sections:

Etymology
Taxonomy and evolution
Anatomy
  Tusks and dentition
  Vibrissae (whiskers)
  Skin
Life history
  Reproduction
  Migration
Ecology
  Range and habitat
  Diet
  Predators
Relation to humans
  Conservation
  Culture
See also
References
Further reading
External links

$ ./wiki walrus etymology

You searched for 'walrus' 'etymology'.
Found this wiki page: 'https://en.wikipedia.org/wiki/Walrus'.

Etymology
The origin of the word walrus is thought by J.R.R. Tolkien&#91;5&#93; to derive from a Germanic language, and it has been attributed largely to either the Dutch language or Old Norse. Its first part is thought to derive from a word such as Old Norse valr ("whale") and the second part has been hypothesized to come from the Old Norse word hross ("horse").&#91;6&#93; For example, the Old Norse word hrossvalr means "horse-whale" and is thought to have been passed in an inverted form to both Dutch and the dialects of northern Germany as walros and Walross.&#91;7&#93; An alternative theory is that it comes from the Dutch words wal "shore" and reus "giant".&#91;8&#93;